#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh
# $HOME/.config/polybar/bspwm.sh
udiskie &
wmname LG3D

#pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d                         1 2 3 4 5 6 7 8 9 10

bspc config border_width                0
bspc config window_gap                  4
bspc config top_padding 	            0
bspc config bottom_padding 	            0
bspc config left_padding 	            0
bspc config right_padding 	            0
bspc config focus_follows_pointer       true
bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true

bspc rule -a                            Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^3'
bspc rule -a                            mplayer2 state=floating
bspc rule -a                            Kupfer.py focus=on
bspc rule -a                            Screenkey manage=off
bspc rule -a                            Emacs state=tiled
